import { describe, it, expect } from 'vitest';
import {
  computeRoadNetworkStatus,
  computeTransportCapacity,
  computeTransportDemand,
} from './infrastructure.js';

// ── computeRoadNetworkStatus ──────────────────────────────────────────────────
// Converts inhabited_km2 → hexes (1 hex = 1000 km²), then km required
// (500 km/hex), then credits required (cost_cr_per_km from TL table).
// complete = true when spent_cr >= required_cr (or no inhabited area).
//
// TL 8: cost_mcr_per_km = 0.0100 → cost_cr_per_km = 10 000 Cr/km
// TL 4: cost_mcr_per_km = 0.0040 → cost_cr_per_km =  4 000 Cr/km
// Road cost example:
//   1000 km² → 1 hex → 500 km → TL 8 → 500 × 10 000 = 5 000 000 Cr

describe('computeRoadNetworkStatus()', () => {
  it('no inhabited area → required_cr=0, complete=true', () => {
    const r = computeRoadNetworkStatus(0, 0, 8);
    expect(r.required_cr).toBe(0);
    expect(r.spent_cr).toBe(0);
    expect(r.complete).toBe(true);
  });

  it('1000 km², TL 8, no spending → 5 000 000 Cr required, incomplete', () => {
    const r = computeRoadNetworkStatus(1000, 0, 8);
    expect(r.required_cr).toBe(5_000_000);
    expect(r.spent_cr).toBe(0);
    expect(r.complete).toBe(false);
  });

  it('1000 km², TL 8, exactly funded → complete', () => {
    const r = computeRoadNetworkStatus(1000, 5_000_000, 8);
    expect(r.required_cr).toBe(5_000_000);
    expect(r.spent_cr).toBe(5_000_000);
    expect(r.complete).toBe(true);
  });

  it('1000 km², TL 8, over-funded → complete', () => {
    const r = computeRoadNetworkStatus(1000, 7_000_000, 8);
    expect(r.complete).toBe(true);
  });

  it('2500 km² rounds up to 3 hexes: TL 8 → 15 000 000 Cr', () => {
    // Math.ceil(2500 / 1000) = 3 hexes; 3 × 500 km × 10 000 Cr/km
    const r = computeRoadNetworkStatus(2500, 0, 8);
    expect(r.required_cr).toBe(15_000_000);
    expect(r.complete).toBe(false);
  });

  it('1000 km², TL 4 → 2 000 000 Cr  (4 000 Cr/km)', () => {
    // 500 km × 4 000 Cr/km
    const r = computeRoadNetworkStatus(1000, 0, 4);
    expect(r.required_cr).toBe(2_000_000);
    expect(r.complete).toBe(false);
  });

  it('1000 km², TL 4, partially funded → incomplete', () => {
    const r = computeRoadNetworkStatus(1000, 1_000_000, 4);
    expect(r.spent_cr).toBe(1_000_000);
    expect(r.complete).toBe(false);
  });
});

// ── computeTransportCapacity ──────────────────────────────────────────────────
// Total transport capacity = sum of installed lines' capacity_mt_per_month.
// Unit: million-tonne-km/month (each line's capacity already reflects TL rating).

describe('computeTransportCapacity()', () => {
  it('no lines → 0', () => {
    expect(computeTransportCapacity([])).toBe(0);
  });

  it('one TL-8 line (capacity 30) → 30', () => {
    expect(computeTransportCapacity([
      { from_hex: 'A', to_hex: 'B', capacity_mt_per_month: 30, length_km: 500 },
    ])).toBe(30);
  });

  it('two lines → sum of capacities', () => {
    expect(computeTransportCapacity([
      { from_hex: 'A', to_hex: 'B', capacity_mt_per_month: 30, length_km: 500 },
      { from_hex: 'B', to_hex: 'C', capacity_mt_per_month: 15, length_km: 800 },
    ])).toBe(45);
  });

  it('three lines → sum', () => {
    expect(computeTransportCapacity([
      { from_hex: 'A', to_hex: 'B', capacity_mt_per_month: 10, length_km: 200 },
      { from_hex: 'B', to_hex: 'C', capacity_mt_per_month: 10, length_km: 200 },
      { from_hex: 'C', to_hex: 'D', capacity_mt_per_month: 10, length_km: 200 },
    ])).toBe(30);
  });
});

// ── computeTransportDemand ────────────────────────────────────────────────────
// Demand = raw_materials_t / 1000 + total_laborers / 500
// Represents freight load generated by extracting and moving raw materials
// and supplying the labour force.  Unit: million-tonne-km/month.

describe('computeTransportDemand()', () => {
  it('zero inputs → 0', () => {
    expect(computeTransportDemand(0, 0)).toBe(0);
  });

  it('1000 t raw materials, 0 laborers → 1.0', () => {
    expect(computeTransportDemand(1000, 0)).toBeCloseTo(1.0, 6);
  });

  it('0 t raw materials, 500 laborers → 1.0', () => {
    expect(computeTransportDemand(0, 500)).toBeCloseTo(1.0, 6);
  });

  it('2000 t, 1000 laborers → 4.0  (2.0 + 2.0)', () => {
    expect(computeTransportDemand(2000, 1000)).toBeCloseTo(4.0, 6);
  });

  it('500 t, 250 laborers → 1.0  (0.5 + 0.5)', () => {
    expect(computeTransportDemand(500, 250)).toBeCloseTo(1.0, 6);
  });
});
